Refactoring proposal
badrap/bar-of-progress pull request #17
Opened 2022-05-10 12:53 UTC by dimitri-bourreau

Thanks for your awesome work!

I tried to use your package, but it failed.

Working on it, I did on my project a little refactoring. I want to propose some of it, in case you'd like it.

# Important

I could not change the color of the progress bar, fixed by updating `backgroundColor` with `config.color`.

https://github.com/dimitri-bourreau/bar-of-progress/blob/8e86fdc29406fab7272f39279a5159283912ca4e/src/index.ts#L51

# Minor

We don't need to use the `assign` function to set the config:

https://github.com/dimitri-bourreau/bar-of-progress/blob/8e86fdc29406fab7272f39279a5159283912ca4e/src/index.ts#L36-L41

Because of that, we can now type the `assign` function!

https://github.com/dimitri-bourreau/bar-of-progress/blob/8e86fdc29406fab7272f39279a5159283912ca4e/src/index.ts#L27-L34

`Partial<CSSStyleDeclaration>` needed to update number values to string values on some style.

# Conclusion

I hope it will help, and give some inspiration. 

I humbly propose this, I thank you again for your help, you saved me hours of work!

2022-05-12 11:31 UTC, jviide requested changes
Huge thanks for looking through the code 👏 I made some notes about the proposed changes. As you might tell, the size of the compiled + compressed output is a focus of ours, so several comments address that.

I'm sorry to hear that the currentColor doesn't work. It'd be interesting to know what causes it to not work in some cases, but work elsewhere (e.g. https://codesandbox.io/s/agitated-panini-htfwin). In any case directly setting `backgroundColor: config.color` is a good fix.

## Random ramblings

As a potentionally interesting side note, there was a reason why we originally implemented `assign` with `Object.keys(...).forEach(...)` instead of a for-in loop: A raw for-in loop copies all _enumerable_ properties (i.e. it follows the prototype chain), while the `Object.keys(...).forEach(...)` version copies only the _enumerable_ and _own_ properties.

Now, let's imagine a case where an attacker manages to take advantage of something like a [prototype pollution](https://learn.snyk.io/lessons/prototype-pollution/javascript/) elsewhere in the system. If they manage to control `Object.prototype.cssText` that way, then a raw for-in loop would set the progress bar's `style.cssText`, giving the attacker control of the inline style of the progress bar component. This in turn allows [some nasty shenanigans](https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/11-Client_Side_Testing/05-Testing_for_CSS_Injection), especially with the older browsers.

This can be of course mitigated with a `Object.prototype.hasOwnProperty` check inside the for-in loop, but AFAIK that was more bytes than the `Object.keys` version. `Object.assign` is also "safe" in this regard, as it only assigns _enumerable_ and _own_ properties of the source object.

Arguably this is a _really_ unlikely case, and if someone manages to inject stuff to `Object.prototype` all bets are probably off anyway. But hey, with that small change at least our little library wouldn't then be a step in an exploit chain 🙂

2022-05-12 12:02 UTC, jviide commented
Sorry for the massive wall of text btw 😅

2022-05-13 06:39 UTC, dimitri-bourreau commented
I don't want to get personnal in a PR, but I want to let you know I'm grateful for your review, and I sincerely thank you. 👍
I got to learn a few amazing things, and your point of view is as new for me that it is appealing!
I want to humbly close this PR, and thank you again. 
I guess you've dedicated a significative amount of time on this, it sparkled joy and motivated me (and maybe future readers) to participate to open sourced project.

2022-05-13 06:39 UTC, closed without merging

2022-05-13 10:35 UTC, jviide commented
I'm glad to hear that 🙂

The `backgroundColor: config.color` fix this pull request makes is something we should definitely have, so would you be willing to create a new pull request containing that change (or reopen & modify this one)? Another option would be that I make the change with you as a coauthor for that commit (if that's okay for you), as it's you who discovered and created the fix 👍